/-
Copyright (c) 2026 Josef Greilhuber. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Josef Greilhuber
-/
import Warren.WeakBezout.GradedDim
import Warren.WeakBezout.Regularity
import Mathlib

/-! # Weak Bezout: counting

The dimension count for a weakly regular sequence of homogeneous polynomials: if
`L : Fin n → k[X₁, …, Xₙ]` is a weakly regular sequence of homogeneous polynomials with
`L i` of degree `d i ≥ 1`, and all homogeneous polynomials of degree `≥ T` lie in the ideal
generated by the `L i`, then the quotient by that ideal is finite-dimensional of dimension
`∏ i, d i` (`finrank_quotient_span_eq_prod`).

The proof tracks the graded dimensions `hdim` of the partial quotients
`R ⧸ (L 0, …, L (j-1))` through the Hilbert series `hseries` (a power series over `ℤ`).
Multiplication by `L j` on `R ⧸ (L 0, …, L (j-1))` is injective (weak regularity) and its
cokernel in each degree is the corresponding graded piece of `R ⧸ (L 0, …, L j)`, giving the
recursion `hseries (J ⊔ (ℓ)) = hseries J * (1 - X ^ deg ℓ)` (`hseries_sup`).  Iterating,
`hseries (L 0, …, L (n-1)) = hseries ⊥ * ∏ i, (1 - X ^ d i)`.  Applying the same recursion to
the sequence of variables (which satisfies the required injectivity by monomial inspection)
yields `hseries ⊥ * (1 - X)^n = hseries (X 0, …, X (n-1)) = 1`, so the geometric series
factorization gives `hseries (L 0, …, L (n-1)) = ∏ i, (1 + X + ⋯ + X ^ (d i - 1))`, a
polynomial whose coefficient sum is `∏ i, d i`.
-/

namespace WeakBezout

open MvPolynomial

variable {n : ℕ} {k : Type*} [Field k]

/-! ## The one-step recursion for graded dimensions -/

section Recursion

variable {ℓ : MvPolynomial (Fin n) k} {e : ℕ}

/-- Multiplication by a homogeneous polynomial `ℓ` of degree `e`, as a linear map from the
degree-`s` piece to the degree-`(s + e)` piece. -/
private noncomputable def mulPiece (hℓ : ℓ.IsHomogeneous e) (s : ℕ) :
    homogeneousSubmodule (Fin n) k s →ₗ[k] homogeneousSubmodule (Fin n) k (s + e) :=
  LinearMap.codRestrict _
    ((LinearMap.mulRight k ℓ) ∘ₗ (homogeneousSubmodule (Fin n) k s).subtype)
    fun x => (mem_homogeneousSubmodule _ _).mpr (((mem_homogeneousSubmodule _ _).mp x.2).mul hℓ)

@[simp] private lemma coe_mulPiece (hℓ : ℓ.IsHomogeneous e) (s : ℕ)
    (x : homogeneousSubmodule (Fin n) k s) :
    (mulPiece hℓ s x : MvPolynomial (Fin n) k) = (x : MvPolynomial (Fin n) k) * ℓ :=
  rfl

/-- Multiplication by `ℓ`, descended to the graded pieces of the quotient by `J`. -/
private noncomputable def mulPieceQ (J : Ideal (MvPolynomial (Fin n) k))
    (hℓ : ℓ.IsHomogeneous e) (s : ℕ) :
    (homogeneousSubmodule (Fin n) k s ⧸ idealPiece J s) →ₗ[k]
      (homogeneousSubmodule (Fin n) k (s + e) ⧸ idealPiece J (s + e)) :=
  Submodule.mapQ _ _ (mulPiece hℓ s) (by
    intro x hx
    rw [Submodule.mem_comap, mem_idealPiece, coe_mulPiece]
    exact Ideal.mul_mem_right ℓ J (mem_idealPiece.mp hx))

private lemma mulPieceQ_mk (J : Ideal (MvPolynomial (Fin n) k)) (hℓ : ℓ.IsHomogeneous e)
    (s : ℕ) (x : homogeneousSubmodule (Fin n) k s) :
    mulPieceQ J hℓ s (Submodule.Quotient.mk x) = Submodule.Quotient.mk (mulPiece hℓ s x) :=
  Submodule.mapQ_apply _ _ _ x

/-- The projection between the graded pieces of the quotients by nested ideals `J ≤ J'`. -/
private noncomputable def projPieceQ (J J' : Ideal (MvPolynomial (Fin n) k)) (h : J ≤ J')
    (t : ℕ) :
    (homogeneousSubmodule (Fin n) k t ⧸ idealPiece J t) →ₗ[k]
      (homogeneousSubmodule (Fin n) k t ⧸ idealPiece J' t) :=
  Submodule.mapQ _ _ LinearMap.id fun _ hx => h (mem_idealPiece.mp hx)

private lemma projPieceQ_mk (J J' : Ideal (MvPolynomial (Fin n) k)) (h : J ≤ J') (t : ℕ)
    (x : homogeneousSubmodule (Fin n) k t) :
    projPieceQ J J' h t (Submodule.Quotient.mk x) = Submodule.Quotient.mk x :=
  Submodule.mapQ_apply _ _ _ x

private lemma surjective_projPieceQ (J J' : Ideal (MvPolynomial (Fin n) k)) (h : J ≤ J')
    (t : ℕ) : Function.Surjective (projPieceQ J J' h t) := by
  intro y
  obtain ⟨x, rfl⟩ := Submodule.Quotient.mk_surjective _ y
  exact ⟨Submodule.Quotient.mk x, projPieceQ_mk J J' h t x⟩

private lemma injective_mulPieceQ (J : Ideal (MvPolynomial (Fin n) k))
    (hℓ : ℓ.IsHomogeneous e) (hinj : ∀ c, ℓ * c ∈ J → c ∈ J) (s : ℕ) :
    Function.Injective (mulPieceQ J hℓ s) := by
  rw [← LinearMap.ker_eq_bot, Submodule.eq_bot_iff]
  intro y hy
  obtain ⟨x, rfl⟩ := Submodule.Quotient.mk_surjective _ y
  rw [LinearMap.mem_ker, mulPieceQ_mk, Submodule.Quotient.mk_eq_zero, mem_idealPiece,
    coe_mulPiece] at hy
  rw [Submodule.Quotient.mk_eq_zero, mem_idealPiece]
  exact hinj _ (by rwa [mul_comm])

private lemma ker_projPieceQ (J : Ideal (MvPolynomial (Fin n) k))
    (S : Set (MvPolynomial (Fin n) k)) (hS : ∀ f ∈ S, ∃ e', f.IsHomogeneous e')
    (hJ : J = Ideal.span S) (hℓ : ℓ.IsHomogeneous e) (s : ℕ) :
    LinearMap.ker (projPieceQ J (J ⊔ Ideal.span {ℓ}) le_sup_left (s + e)) =
      LinearMap.range (mulPieceQ J hℓ s) := by
  apply le_antisymm
  · intro y hy
    obtain ⟨y0, rfl⟩ := Submodule.Quotient.mk_surjective _ y
    rw [LinearMap.mem_ker, projPieceQ_mk, Submodule.Quotient.mk_eq_zero, mem_idealPiece] at hy
    obtain ⟨g, hg, z, hz, hgz⟩ := Submodule.mem_sup.mp hy
    obtain ⟨c, rfl⟩ := Ideal.mem_span_singleton'.mp hz
    have hy0 : (y0 : MvPolynomial (Fin n) k) =
        homogeneousComponent (s + e) g + homogeneousComponent s c * ℓ := by
      have h := congrArg (homogeneousComponent (s + e)) hgz
      rw [map_add, homogeneousComponent_mul_isHomogeneous_right hℓ,
        homogeneousComponent_of_mem y0.2, if_pos rfl] at h
      exact h.symm
    have hgmem : homogeneousComponent (s + e) g ∈ J := by
      rw [hJ]
      exact homogeneousComponent_mem_ideal_span hS (hJ ▸ hg) _
    rw [LinearMap.mem_range]
    refine ⟨Submodule.Quotient.mk ⟨homogeneousComponent s c, homogeneousComponent_mem _ _⟩, ?_⟩
    rw [mulPieceQ_mk, Submodule.Quotient.eq, mem_idealPiece, Submodule.coe_sub, coe_mulPiece,
      hy0]
    have harith :
        (⟨homogeneousComponent s c, homogeneousComponent_mem s c⟩ :
            homogeneousSubmodule (Fin n) k s) * ℓ -
          (homogeneousComponent (s + e) g + homogeneousComponent s c * ℓ) =
          -(homogeneousComponent (s + e) g) := by
      ring
    rw [harith]
    exact neg_mem hgmem
  · intro y hy
    obtain ⟨x, rfl⟩ := LinearMap.mem_range.mp hy
    obtain ⟨x0, rfl⟩ := Submodule.Quotient.mk_surjective _ x
    rw [mulPieceQ_mk, LinearMap.mem_ker, projPieceQ_mk, Submodule.Quotient.mk_eq_zero,
      mem_idealPiece, coe_mulPiece]
    exact Submodule.mem_sup_right (Ideal.mem_span_singleton'.mpr ⟨_, rfl⟩)

/-- The main step of the graded dimension recursion: for a homogeneously generated ideal `J`
and `ℓ` homogeneous of degree `e` with `ℓ` regular modulo `J`, adding `ℓ` to `J` removes
one copy of the Hilbert function shifted by `e`. -/
theorem hdim_sup_add_hdim (J : Ideal (MvPolynomial (Fin n) k))
    (S : Set (MvPolynomial (Fin n) k)) (hS : ∀ f ∈ S, ∃ e', f.IsHomogeneous e')
    (hJ : J = Ideal.span S) (hℓ : ℓ.IsHomogeneous e)
    (hinj : ∀ c, ℓ * c ∈ J → c ∈ J) (s : ℕ) :
    hdim (J ⊔ Ideal.span {ℓ}) (s + e) + hdim J s = hdim J (s + e) := by
  have h1 := LinearMap.finrank_range_add_finrank_ker
    (projPieceQ J (J ⊔ Ideal.span {ℓ}) le_sup_left (s + e))
  rw [LinearMap.range_eq_top.mpr (surjective_projPieceQ J (J ⊔ Ideal.span {ℓ}) le_sup_left
    (s + e)), finrank_top, ker_projPieceQ J S hS hJ hℓ s,
    LinearMap.finrank_range_of_inj (injective_mulPieceQ J hℓ hinj s)] at h1
  exact h1

/-- Below the degree of `ℓ`, adding `ℓ` to a homogeneously generated ideal does not change
the graded pieces. -/
theorem hdim_sup_of_lt (J : Ideal (MvPolynomial (Fin n) k))
    (S : Set (MvPolynomial (Fin n) k)) (hS : ∀ f ∈ S, ∃ e', f.IsHomogeneous e')
    (hJ : J = Ideal.span S) (hℓ : ℓ.IsHomogeneous e) {t : ℕ} (ht : t < e) :
    hdim (J ⊔ Ideal.span {ℓ}) t = hdim J t := by
  have hpiece : idealPiece (J ⊔ Ideal.span {ℓ}) t = idealPiece J t := by
    apply le_antisymm
    · intro x hx
      rw [mem_idealPiece] at hx ⊢
      obtain ⟨g, hg, z, hz, hgz⟩ := Submodule.mem_sup.mp hx
      obtain ⟨c, rfl⟩ := Ideal.mem_span_singleton'.mp hz
      have hx0 : (x : MvPolynomial (Fin n) k) = homogeneousComponent t g := by
        have h := congrArg (homogeneousComponent t) hgz
        rw [map_add, homogeneousComponent_mul_of_lt hℓ _ ht, add_zero,
          homogeneousComponent_of_mem x.2, if_pos rfl] at h
        exact h.symm
      rw [hx0, hJ]
      exact homogeneousComponent_mem_ideal_span hS (hJ ▸ hg) _
    · intro x hx
      rw [mem_idealPiece] at hx ⊢
      exact Submodule.mem_sup_left hx
  simp only [hdim]
  rw [hpiece]

end Recursion

/-! ## Hilbert series -/

/-- The Hilbert series of `R ⧸ I` with respect to the grading by degree, as a power series
over `ℤ`. -/
noncomputable def hseries (I : Ideal (MvPolynomial (Fin n) k)) : PowerSeries ℤ :=
  PowerSeries.mk fun t => (hdim I t : ℤ)

@[simp] theorem coeff_hseries (I : Ideal (MvPolynomial (Fin n) k)) (t : ℕ) :
    PowerSeries.coeff t (hseries I) = (hdim I t : ℤ) :=
  PowerSeries.coeff_mk t _

/-- The Hilbert series recursion: adding to a homogeneously generated ideal `J` a regular
homogeneous element of degree `e` multiplies the Hilbert series by `1 - X ^ e`. -/
theorem hseries_sup (J : Ideal (MvPolynomial (Fin n) k))
    (S : Set (MvPolynomial (Fin n) k)) (hS : ∀ f ∈ S, ∃ e', f.IsHomogeneous e')
    (hJ : J = Ideal.span S) {ℓ : MvPolynomial (Fin n) k} {e : ℕ} (hℓ : ℓ.IsHomogeneous e)
    (hinj : ∀ c, ℓ * c ∈ J → c ∈ J) :
    hseries (J ⊔ Ideal.span {ℓ}) = hseries J * (1 - PowerSeries.X ^ e) := by
  ext t
  rw [coeff_hseries, mul_sub, mul_one, map_sub, coeff_hseries,
    PowerSeries.coeff_mul_X_pow']
  rcases Nat.lt_or_ge t e with h | h
  · rw [if_neg (by omega), sub_zero, hdim_sup_of_lt J S hS hJ hℓ h]
  · obtain ⟨s, rfl⟩ : ∃ s, t = s + e := ⟨t - e, by omega⟩
    rw [if_pos h, Nat.add_sub_cancel, coeff_hseries]
    have hrec := hdim_sup_add_hdim J S hS hJ hℓ hinj s
    omega

/-! ## Partial spans and the iterated recursion -/

/-- The ideal generated by the first `j` members of the family `L`. -/
noncomputable def partialSpan (L : Fin n → MvPolynomial (Fin n) k) (j : ℕ) :
    Ideal (MvPolynomial (Fin n) k) :=
  Ideal.span (L '' {i : Fin n | (i : ℕ) < j})

theorem partialSpan_zero (L : Fin n → MvPolynomial (Fin n) k) : partialSpan L 0 = ⊥ := by
  have h : {i : Fin n | (i : ℕ) < 0} = ∅ := by
    ext i
    simp
  rw [partialSpan, h, Set.image_empty, Ideal.span_empty]

theorem partialSpan_top (L : Fin n → MvPolynomial (Fin n) k) :
    partialSpan L n = Ideal.span (Set.range L) := by
  have h : {i : Fin n | (i : ℕ) < n} = Set.univ := by
    ext i
    simp
  rw [partialSpan, h, Set.image_univ]

theorem partialSpan_succ (L : Fin n → MvPolynomial (Fin n) k) {j : ℕ} (hj : j < n) :
    partialSpan L (j + 1) = partialSpan L j ⊔ Ideal.span {L ⟨j, hj⟩} := by
  rw [partialSpan, partialSpan, ← Ideal.span_union]
  congr 1
  ext f
  simp only [Set.mem_image, Set.mem_union, Set.mem_setOf_eq, Set.mem_singleton_iff]
  constructor
  · rintro ⟨i, hi, rfl⟩
    rcases Nat.lt_succ_iff_lt_or_eq.mp hi with h | h
    · exact Or.inl ⟨i, h, rfl⟩
    · exact Or.inr (congrArg L (Fin.ext h))
  · rintro (⟨i, hi, rfl⟩ | rfl)
    · exact ⟨i, Nat.lt_succ_of_lt hi, rfl⟩
    · exact ⟨⟨j, hj⟩, Nat.lt_succ_self j, rfl⟩

theorem forall_mem_image_partialSpan {L : Fin n → MvPolynomial (Fin n) k}
    {d : Fin n → ℕ} (hhom : ∀ i, (L i).IsHomogeneous (d i)) (j : ℕ) :
    ∀ f ∈ L '' {i : Fin n | (i : ℕ) < j}, ∃ e, f.IsHomogeneous e := by
  rintro f ⟨i, _, rfl⟩
  exact ⟨d i, hhom i⟩

/-- Iterating the Hilbert series recursion over the family `L`. -/
theorem hseries_partialSpan (L : Fin n → MvPolynomial (Fin n) k) (d : Fin n → ℕ)
    (hhom : ∀ i, (L i).IsHomogeneous (d i))
    (hinj : ∀ (j : Fin n) (c : MvPolynomial (Fin n) k),
      L j * c ∈ partialSpan L (j : ℕ) → c ∈ partialSpan L (j : ℕ)) :
    ∀ j, j ≤ n → hseries (partialSpan L j) =
      hseries (⊥ : Ideal (MvPolynomial (Fin n) k)) *
        ∏ i ∈ Finset.univ.filter (fun i : Fin n => (i : ℕ) < j), (1 - PowerSeries.X ^ d i) := by
  intro j
  induction j with
  | zero =>
    intro _
    have hfil : Finset.univ.filter (fun i : Fin n => (i : ℕ) < 0) = ∅ := by
      ext i
      simp
    rw [partialSpan_zero, hfil, Finset.prod_empty, mul_one]
  | succ j ih =>
    intro hj
    have hjn : j < n := hj
    have hfil : Finset.univ.filter (fun i : Fin n => (i : ℕ) < j + 1) =
        insert ⟨j, hjn⟩ (Finset.univ.filter fun i : Fin n => (i : ℕ) < j) := by
      ext i
      simp only [Finset.mem_filter, Finset.mem_univ, true_and, Finset.mem_insert, Fin.ext_iff]
      omega
    rw [partialSpan_succ L hjn,
      hseries_sup (partialSpan L j) (L '' {i : Fin n | (i : ℕ) < j})
        (forall_mem_image_partialSpan hhom j) rfl (hhom ⟨j, hjn⟩) (hinj ⟨j, hjn⟩),
      ih (Nat.le_of_succ_le hj), hfil, Finset.prod_insert (by simp)]
    ring

/-! ## Weak regularity supplies the injectivity hypothesis -/

private theorem smul_top_ideal (I : Ideal (MvPolynomial (Fin n) k)) :
    I • (⊤ : Submodule (MvPolynomial (Fin n) k) (MvPolynomial (Fin n) k)) = I := by
  rw [Ideal.smul_eq_mul, Ideal.mul_top]

private theorem ofList_take_partialSpan (L : Fin n → MvPolynomial (Fin n) k) (j : Fin n) :
    Ideal.ofList ((List.ofFn L).take (j : ℕ)) = partialSpan L (j : ℕ) :=
  ofList_take_ofFn L (j : ℕ)

/-- Weak regularity of the sequence `L` yields the injectivity of multiplication by `L j`
modulo the ideal generated by the preceding members. -/
theorem mul_mem_partialSpan_of_isWeaklyRegular {L : Fin n → MvPolynomial (Fin n) k}
    (hreg : RingTheory.Sequence.IsWeaklyRegular (MvPolynomial (Fin n) k) (List.ofFn L))
    (j : Fin n) (c : MvPolynomial (Fin n) k)
    (hc : L j * c ∈ partialSpan L (j : ℕ)) : c ∈ partialSpan L (j : ℕ) := by
  have hlen : (j : ℕ) < (List.ofFn L).length := by
    simp
  have hr := hreg.regular_mod_prev (j : ℕ) hlen
  have hget : (List.ofFn L)[(j : ℕ)] = L j := by
    simp
  rw [hget, ofList_take_partialSpan L j] at hr
  have h1 : (Submodule.Quotient.mk (L j * c) : MvPolynomial (Fin n) k ⧸
      (partialSpan L (j : ℕ) • ⊤ :
        Submodule (MvPolynomial (Fin n) k) (MvPolynomial (Fin n) k))) = 0 := by
    rw [Submodule.Quotient.mk_eq_zero, smul_top_ideal]
    exact hc
  have h2 : (Submodule.Quotient.mk c : MvPolynomial (Fin n) k ⧸
      (partialSpan L (j : ℕ) • ⊤ :
        Submodule (MvPolynomial (Fin n) k) (MvPolynomial (Fin n) k))) = 0 := by
    apply hr
    change L j • Submodule.Quotient.mk c = L j • (0 : _)
    rw [smul_zero, ← Submodule.Quotient.mk_smul, smul_eq_mul]
    exact h1
  rwa [Submodule.Quotient.mk_eq_zero, smul_top_ideal] at h2

/-! ## The variable sequence -/

/-- The injectivity hypothesis for the sequence of variables, by inspecting monomials. -/
theorem X_mul_mem_partialSpan (j : Fin n) (c : MvPolynomial (Fin n) k)
    (hc : X j * c ∈ partialSpan X (j : ℕ)) : c ∈ partialSpan X (j : ℕ) := by
  simp only [partialSpan] at hc ⊢
  rw [mem_ideal_span_X_image] at hc ⊢
  intro m hm
  have hm' : Finsupp.single j 1 + m ∈ (X j * c).support := by
    rw [MvPolynomial.mem_support_iff, coeff_X_mul]
    exact MvPolynomial.mem_support_iff.mp hm
  obtain ⟨i, hi, hine⟩ := hc _ hm'
  refine ⟨i, hi, ?_⟩
  have hij : i ≠ j := by
    rintro rfl
    simp only [Set.mem_setOf_eq] at hi
    exact lt_irrefl _ hi
  rwa [Finsupp.add_apply, Finsupp.single_apply, if_neg fun h => hij h.symm, zero_add] at hine

/-- The quotient by the ideal of all variables has Hilbert series `1`. -/
theorem hseries_span_X :
    hseries (Ideal.span (Set.range (X : Fin n → MvPolynomial (Fin n) k))) = 1 := by
  ext t
  rw [coeff_hseries, PowerSeries.coeff_one]
  rcases t with _ | t
  · rw [if_pos rfl]
    have h0 : idealPiece (Ideal.span (Set.range (X : Fin n → MvPolynomial (Fin n) k))) 0 =
        (⊥ : Submodule k (homogeneousSubmodule (Fin n) k 0)) := by
      rw [Submodule.eq_bot_iff]
      intro x hx
      rw [mem_idealPiece, ← Set.image_univ, mem_ideal_span_X_image] at hx
      have hxz : (x : MvPolynomial (Fin n) k) = 0 := by
        by_contra hne
        obtain ⟨m, hm⟩ := MvPolynomial.support_nonempty.mpr hne
        obtain ⟨i, _, hi⟩ := hx m hm
        have hdeg : m.degree = 0 := by
          by_contra hd
          exact MvPolynomial.mem_support_iff.mp hm
            (((mem_homogeneousSubmodule _ _).mp x.2).coeff_eq_zero hd)
        rw [(Finsupp.degree_eq_zero_iff m).mp hdeg] at hi
        simp at hi
      exact Subtype.ext hxz
    have h1 : hdim (Ideal.span (Set.range (X : Fin n → MvPolynomial (Fin n) k))) 0 = 1 := by
      have heq : hdim (Ideal.span (Set.range (X : Fin n → MvPolynomial (Fin n) k))) 0 =
          Module.finrank k (homogeneousSubmodule (Fin n) k 0) :=
        (Submodule.quotEquivOfEqBot _ h0).finrank_eq
      rw [heq, homogeneousSubmodule_zero, Submodule.one_eq_span]
      exact finrank_span_singleton one_ne_zero
    rw [h1, Nat.cast_one]
  · rw [if_neg (Nat.succ_ne_zero t)]
    have hz : hdim (Ideal.span (Set.range (X : Fin n → MvPolynomial (Fin n) k))) (t + 1) = 0 := by
      apply hdim_eq_zero_of_le
      intro f hf
      rw [Submodule.restrictScalars_mem, ← Set.image_univ, mem_ideal_span_X_image]
      intro m hm
      have hdeg : m.degree = t + 1 := by
        by_contra hd
        exact MvPolynomial.mem_support_iff.mp hm
          (((mem_homogeneousSubmodule _ _).mp hf).coeff_eq_zero hd)
      by_contra hall
      push Not at hall
      have hm0 : m = 0 := by
        ext i
        simpa using hall i (Set.mem_univ i)
      rw [hm0] at hdeg
      simp at hdeg
    rw [hz, Nat.cast_zero]

/-! ## The final count -/

set_option linter.unusedVariables false in
/-- **Weak Bézout dimension count.** If `L` is a weakly regular sequence of homogeneous
polynomials of degrees `d i ≥ 1` in `k[X₁, …, Xₙ]` such that all homogeneous polynomials of
degree `≥ T` lie in the ideal generated by the `L i`, then the quotient by that ideal is a
finite-dimensional `k`-vector space of dimension `∏ i, d i`.

(The hypothesis `hd` is kept for faithfulness to the informal statement; this proof route does
not need it.) -/
theorem finrank_quotient_span_eq_prod {n : ℕ} {k : Type*} [Field k]
    (L : Fin n → MvPolynomial (Fin n) k) (d : Fin n → ℕ)
    (hhom : ∀ i, (L i).IsHomogeneous (d i)) (hd : ∀ i, 1 ≤ d i)
    (hreg : RingTheory.Sequence.IsWeaklyRegular (MvPolynomial (Fin n) k) (List.ofFn L))
    (T : ℕ)
    (hT : ∀ t, T ≤ t → MvPolynomial.homogeneousSubmodule (Fin n) k t ≤
      Submodule.restrictScalars k (Ideal.span (Set.range L))) :
    FiniteDimensional k (MvPolynomial (Fin n) k ⧸ Ideal.span (Set.range L)) ∧
      Module.finrank k (MvPolynomial (Fin n) k ⧸ Ideal.span (Set.range L)) = ∏ i, d i := by
  classical
  have hfd : FiniteDimensional k (MvPolynomial (Fin n) k ⧸ Ideal.span (Set.range L)) :=
    finiteDimensional_quotient _ T hT
  refine ⟨hfd, ?_⟩
  have hfilt : (Finset.univ.filter fun i : Fin n => (i : ℕ) < n) = Finset.univ := by
    ext i
    simp
  -- Hilbert series of the span of `L`
  have hchainL : hseries (Ideal.span (Set.range L)) =
      hseries (⊥ : Ideal (MvPolynomial (Fin n) k)) * ∏ i, (1 - PowerSeries.X ^ d i) := by
    have h := hseries_partialSpan L d hhom
      (fun j => mul_mem_partialSpan_of_isWeaklyRegular hreg j) n le_rfl
    rwa [partialSpan_top, hfilt] at h
  -- Hilbert series of the span of the variables
  have hchainX : hseries (Ideal.span (Set.range (X : Fin n → MvPolynomial (Fin n) k))) =
      hseries (⊥ : Ideal (MvPolynomial (Fin n) k)) * (1 - PowerSeries.X) ^ n := by
    have h := hseries_partialSpan (X : Fin n → MvPolynomial (Fin n) k) (fun _ => 1)
      (fun i => isHomogeneous_X k i) X_mul_mem_partialSpan n le_rfl
    rw [partialSpan_top, hfilt] at h
    simpa [Finset.prod_const, Finset.card_univ] using h
  have hbase : hseries (⊥ : Ideal (MvPolynomial (Fin n) k)) * (1 - PowerSeries.X) ^ n = 1 := by
    rw [← hchainX, hseries_span_X]
  -- geometric series factorization
  have hgeom : ∀ i : Fin n, (1 - PowerSeries.X ^ d i : PowerSeries ℤ) =
      (1 - PowerSeries.X) * ∑ s ∈ Finset.range (d i), PowerSeries.X ^ s := by
    intro i
    have h := mul_geom_sum (PowerSeries.X : PowerSeries ℤ) (d i)
    linear_combination h
  have hmain : hseries (Ideal.span (Set.range L)) =
      ∏ i, ∑ s ∈ Finset.range (d i), (PowerSeries.X : PowerSeries ℤ) ^ s := by
    calc hseries (Ideal.span (Set.range L))
        = hseries (⊥ : Ideal (MvPolynomial (Fin n) k)) * ∏ i, (1 - PowerSeries.X ^ d i) :=
          hchainL
      _ = hseries (⊥ : Ideal (MvPolynomial (Fin n) k)) *
            ∏ i, ((1 - PowerSeries.X) * ∑ s ∈ Finset.range (d i), PowerSeries.X ^ s) := by
          rw [Finset.prod_congr rfl fun i _ => hgeom i]
      _ = (hseries (⊥ : Ideal (MvPolynomial (Fin n) k)) * (1 - PowerSeries.X) ^ n) *
            ∏ i, ∑ s ∈ Finset.range (d i), PowerSeries.X ^ s := by
          rw [Finset.prod_mul_distrib, Finset.prod_const, Finset.card_univ, Fintype.card_fin]
          ring
      _ = ∏ i, ∑ s ∈ Finset.range (d i), (PowerSeries.X : PowerSeries ℤ) ^ s := by
          rw [hbase, one_mul]
  -- the corresponding polynomial
  have hQcoe : ((∏ i, ∑ s ∈ Finset.range (d i), Polynomial.X ^ s : Polynomial ℤ) :
      PowerSeries ℤ) = ∏ i, ∑ s ∈ Finset.range (d i), (PowerSeries.X : PowerSeries ℤ) ^ s := by
    rw [← Polynomial.coeToPowerSeries.ringHom_apply, map_prod]
    refine Finset.prod_congr rfl fun i _ => ?_
    rw [map_sum]
    refine Finset.sum_congr rfl fun s _ => ?_
    rw [map_pow, Polynomial.coeToPowerSeries.ringHom_apply, Polynomial.coe_X]
  set Q : Polynomial ℤ := ∏ i, ∑ s ∈ Finset.range (d i), Polynomial.X ^ s with hQdef
  have hcoeff : ∀ t, (hdim (Ideal.span (Set.range L)) t : ℤ) = Q.coeff t := by
    intro t
    have h := congrArg (PowerSeries.coeff t) hmain
    rw [coeff_hseries] at h
    rw [h, ← hQcoe, Polynomial.coeff_coe]
  -- summing the coefficients
  have hsum : Module.finrank k (MvPolynomial (Fin n) k ⧸ Ideal.span (Set.range L)) =
      ∑ t ∈ Finset.range T, hdim (Ideal.span (Set.range L)) t := by
    have hS : ∀ f ∈ Set.range L, ∃ e, f.IsHomogeneous e := by
      rintro f ⟨i, rfl⟩
      exact ⟨d i, hhom i⟩
    exact finrank_quotient_eq_sum_hdim _ (Set.range L) hS rfl T hT
  have hZ : (∑ t ∈ Finset.range T, (hdim (Ideal.span (Set.range L)) t : ℤ)) =
      ∏ i, (d i : ℤ) := by
    calc ∑ t ∈ Finset.range T, (hdim (Ideal.span (Set.range L)) t : ℤ)
        = ∑ t ∈ Finset.range (max T (Q.natDegree + 1)),
            (hdim (Ideal.span (Set.range L)) t : ℤ) := by
          refine Finset.sum_subset (Finset.range_subset_range.mpr (le_max_left _ _))
            fun t _ ht => ?_
          rw [hdim_eq_zero_of_le (hT t (by simpa using ht)), Nat.cast_zero]
      _ = ∑ t ∈ Finset.range (max T (Q.natDegree + 1)), Q.coeff t :=
          Finset.sum_congr rfl fun t _ => hcoeff t
      _ = ∑ t ∈ Finset.range (Q.natDegree + 1), Q.coeff t := by
          refine (Finset.sum_subset (Finset.range_subset_range.mpr (le_max_right _ _))
            fun t _ ht => ?_).symm
          refine Polynomial.coeff_eq_zero_of_natDegree_lt ?_
          have hBt : Q.natDegree + 1 ≤ t := by
            simpa using ht
          omega
      _ = Q.eval 1 := by
          rw [Polynomial.eval_eq_sum_range]
          exact (Finset.sum_congr rfl fun t _ => by rw [one_pow, mul_one]).symm
      _ = ∏ i, (d i : ℤ) := by
          rw [hQdef, Polynomial.eval_prod]
          refine Finset.prod_congr rfl fun i _ => ?_
          rw [Polynomial.eval_finsetSum]
          simp
  rw [hsum]
  exact_mod_cast hZ

end WeakBezout
