/-
Copyright (c) 2026 Josef Greilhuber. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Josef Greilhuber
-/
import Mathlib

/-! # Weak Bezout: graded dimensions

For an ideal `I` of `R = k[X₁, …, Xₙ]` and `t : ℕ` we define `hdim I t`, the `k`-dimension of
the degree-`t` graded piece of `R ⧸ I`, i.e. of the quotient of the space of homogeneous
polynomials of degree `t` by its intersection with `I`.

The main result of this file is `finrank_quotient_eq_sum_hdim`: when `I` is generated by
homogeneous elements and every homogeneous polynomial of degree `≥ T` lies in `I`, the total
`k`-dimension of `R ⧸ I` is `∑ t < T, hdim I t`.

Along the way we prove:
* `homogeneousComponent_mul_isHomogeneous_right` and `homogeneousComponent_mul_of_lt`:
  homogeneous components of a product with a homogeneous polynomial;
* `homogeneousComponent_mem_ideal_span`: the homogeneous components of an element of a
  homogeneously generated ideal stay in the ideal;
* the instance `FiniteDimensional k (homogeneousSubmodule (Fin n) k t)`;
* `finiteDimensional_quotient`: the vanishing bound alone makes `R ⧸ I` finite-dimensional.
-/

namespace WeakBezout

open MvPolynomial

section ComponentMul

variable {σ : Type*} {R : Type*} [CommSemiring R]

/-- Multiplying by a homogeneous polynomial of degree `e` shifts homogeneous components by `e`:
the degree-`(s + e)` component of `c * q` is the degree-`s` component of `c` times `q`. -/
theorem homogeneousComponent_mul_isHomogeneous_right {q : MvPolynomial σ R} {e : ℕ}
    (hq : q.IsHomogeneous e) (c : MvPolynomial σ R) (s : ℕ) :
    homogeneousComponent (s + e) (c * q) = homogeneousComponent s c * q := by
  classical
  ext m
  rw [coeff_homogeneousComponent, coeff_mul, coeff_mul]
  simp only [coeff_homogeneousComponent]
  split_ifs with hm
  · refine Finset.sum_congr rfl fun x hx => ?_
    rw [Finset.mem_antidiagonal] at hx
    by_cases hq2 : coeff x.2 q = 0
    · rw [hq2, mul_zero, mul_zero]
    · have h2 : x.2.degree = e := by
        by_contra h
        exact hq2 (hq.coeff_eq_zero h)
      have hdeg : m.degree = x.1.degree + x.2.degree := by
        rw [← hx, map_add]
      rw [if_pos (by omega)]
  · symm
    refine Finset.sum_eq_zero fun x hx => ?_
    rw [Finset.mem_antidiagonal] at hx
    by_cases hq2 : coeff x.2 q = 0
    · rw [hq2, mul_zero]
    · have h2 : x.2.degree = e := by
        by_contra h
        exact hq2 (hq.coeff_eq_zero h)
      have hdeg : m.degree = x.1.degree + x.2.degree := by
        rw [← hx, map_add]
      rw [if_neg (by omega), zero_mul]

/-- The homogeneous components of `c * q` in degrees below the degree of the homogeneous
polynomial `q` vanish. -/
theorem homogeneousComponent_mul_of_lt {q : MvPolynomial σ R} {e : ℕ}
    (hq : q.IsHomogeneous e) (c : MvPolynomial σ R) {t : ℕ} (ht : t < e) :
    homogeneousComponent t (c * q) = 0 := by
  classical
  ext m
  rw [coeff_homogeneousComponent, coeff_zero]
  split_ifs with hm
  · rw [coeff_mul]
    refine Finset.sum_eq_zero fun x hx => ?_
    rw [Finset.mem_antidiagonal] at hx
    have hdeg : m.degree = x.1.degree + x.2.degree := by
      rw [← hx, map_add]
    rw [hq.coeff_eq_zero (by omega), mul_zero]
  · rfl

/-- Homogeneous components of an element of an ideal generated by homogeneous polynomials
stay in the ideal. -/
theorem homogeneousComponent_mem_ideal_span {S : Set (MvPolynomial σ R)}
    (hS : ∀ f ∈ S, ∃ e, f.IsHomogeneous e) {f : MvPolynomial σ R}
    (hf : f ∈ Ideal.span S) (t : ℕ) :
    homogeneousComponent t f ∈ Ideal.span S := by
  obtain ⟨c, hsupp, rfl⟩ := Submodule.mem_span_set.mp hf
  rw [Finsupp.sum, map_sum]
  refine Ideal.sum_mem _ fun q hq => ?_
  obtain ⟨e, he⟩ := hS q (hsupp hq)
  rw [smul_eq_mul]
  rcases Nat.lt_or_ge t e with h | h
  · rw [homogeneousComponent_mul_of_lt he _ h]
    exact Submodule.zero_mem _
  · obtain ⟨s, rfl⟩ : ∃ s, t = s + e := ⟨t - e, by omega⟩
    rw [homogeneousComponent_mul_isHomogeneous_right he]
    exact Ideal.mul_mem_left _ _ (Ideal.subset_span (hsupp hq))

end ComponentMul

variable {n : ℕ} {k : Type*} [Field k]

/-- The space of homogeneous polynomials of a fixed degree in finitely many variables is
finite-dimensional. -/
instance (t : ℕ) : FiniteDimensional k (homogeneousSubmodule (Fin n) k t) := by
  apply Submodule.finiteDimensional_of_le (S₂ := restrictTotalDegree (Fin n) k t)
  intro f hf
  rw [mem_restrictTotalDegree]
  exact ((mem_homogeneousSubmodule _ _).mp hf).totalDegree_le

/-- The degree-`t` piece of an ideal `I`, as a `k`-submodule of the space of homogeneous
polynomials of degree `t`. -/
noncomputable def idealPiece (I : Ideal (MvPolynomial (Fin n) k)) (t : ℕ) :
    Submodule k (homogeneousSubmodule (Fin n) k t) :=
  Submodule.comap (homogeneousSubmodule (Fin n) k t).subtype (Submodule.restrictScalars k I)

@[simp] theorem mem_idealPiece {I : Ideal (MvPolynomial (Fin n) k)} {t : ℕ}
    {x : homogeneousSubmodule (Fin n) k t} :
    x ∈ idealPiece I t ↔ (x : MvPolynomial (Fin n) k) ∈ I :=
  Iff.rfl

/-- `hdim I t` is the `k`-dimension of the degree-`t` graded piece of
`k[X₁, …, Xₙ] ⧸ I`, i.e. of the space of homogeneous polynomials of degree `t` modulo those
lying in `I`. -/
noncomputable def hdim (I : Ideal (MvPolynomial (Fin n) k)) (t : ℕ) : ℕ :=
  Module.finrank k (homogeneousSubmodule (Fin n) k t ⧸ idealPiece I t)

/-- If every homogeneous polynomial of degree `t` lies in `I`, the degree-`t` piece of the
quotient vanishes. -/
theorem hdim_eq_zero_of_le {I : Ideal (MvPolynomial (Fin n) k)} {t : ℕ}
    (h : homogeneousSubmodule (Fin n) k t ≤ Submodule.restrictScalars k I) :
    hdim I t = 0 := by
  have htop : idealPiece I t = ⊤ := Submodule.comap_subtype_eq_top.mpr h
  have : Subsingleton (homogeneousSubmodule (Fin n) k t ⧸ idealPiece I t) :=
    Submodule.Quotient.subsingleton_iff.mpr htop
  exact Module.finrank_zero_of_subsingleton

/-- The `k`-linear map assembling the homogeneous pieces of degree `< T` into `R ⧸ I`. -/
noncomputable def piecesToQuotient (I : Ideal (MvPolynomial (Fin n) k)) (T : ℕ) :
    ((t : Fin T) → homogeneousSubmodule (Fin n) k (t : ℕ)) →ₗ[k]
      MvPolynomial (Fin n) k ⧸ I :=
  ∑ t : Fin T, ((Ideal.Quotient.mkₐ k I).toLinearMap ∘ₗ
    (homogeneousSubmodule (Fin n) k (t : ℕ)).subtype) ∘ₗ LinearMap.proj t

theorem piecesToQuotient_apply (I : Ideal (MvPolynomial (Fin n) k)) (T : ℕ)
    (v : (t : Fin T) → homogeneousSubmodule (Fin n) k (t : ℕ)) :
    piecesToQuotient I T v = ∑ t : Fin T, Ideal.Quotient.mk I (v t : MvPolynomial (Fin n) k) := by
  simp [piecesToQuotient]

/-- If every homogeneous polynomial of degree `≥ T` lies in `I`, then the homogeneous pieces of
degree `< T` cover the whole quotient `R ⧸ I`. -/
theorem surjective_piecesToQuotient (I : Ideal (MvPolynomial (Fin n) k)) (T : ℕ)
    (hT : ∀ t, T ≤ t → homogeneousSubmodule (Fin n) k t ≤ Submodule.restrictScalars k I) :
    Function.Surjective (piecesToQuotient I T) := by
  intro x
  obtain ⟨f, rfl⟩ := Ideal.Quotient.mk_surjective x
  refine ⟨fun t => ⟨homogeneousComponent (t : ℕ) f, homogeneousComponent_mem _ f⟩, ?_⟩
  rw [piecesToQuotient_apply]
  calc
    ∑ t : Fin T, Ideal.Quotient.mk I (homogeneousComponent (t : ℕ) f)
        = ∑ i ∈ Finset.range T, Ideal.Quotient.mk I (homogeneousComponent i f) :=
      Fin.sum_univ_eq_sum_range (fun i => Ideal.Quotient.mk I (homogeneousComponent i f)) T
    _ = ∑ i ∈ Finset.range (max T (f.totalDegree + 1)),
          Ideal.Quotient.mk I (homogeneousComponent i f) := by
      refine Finset.sum_subset ?_ fun i _ hi => ?_
      · exact Finset.range_subset_range.mpr (le_max_left _ _)
      · rw [Ideal.Quotient.eq_zero_iff_mem]
        exact hT i (by simpa using hi) (homogeneousComponent_mem i f)
    _ = Ideal.Quotient.mk I
          (∑ i ∈ Finset.range (max T (f.totalDegree + 1)), homogeneousComponent i f) :=
      (map_sum _ _ _).symm
    _ = Ideal.Quotient.mk I f := by
      congr 1
      calc
        ∑ i ∈ Finset.range (max T (f.totalDegree + 1)), homogeneousComponent i f
            = ∑ i ∈ Finset.range (f.totalDegree + 1), homogeneousComponent i f := by
          refine (Finset.sum_subset ?_ fun i _ hi => ?_).symm
          · exact Finset.range_subset_range.mpr (le_max_right _ _)
          · exact homogeneousComponent_eq_zero i f (by simp at hi; omega)
        _ = f := sum_homogeneousComponent f

/-- If every homogeneous polynomial of degree `≥ T` lies in `I`, then `R ⧸ I` is
finite-dimensional over `k`. -/
theorem finiteDimensional_quotient (I : Ideal (MvPolynomial (Fin n) k)) (T : ℕ)
    (hT : ∀ t, T ≤ t → homogeneousSubmodule (Fin n) k t ≤ Submodule.restrictScalars k I) :
    FiniteDimensional k (MvPolynomial (Fin n) k ⧸ I) :=
  Module.Finite.of_surjective (piecesToQuotient I T) (surjective_piecesToQuotient I T hT)

/-- For a homogeneously generated ideal `I`, a sum of homogeneous elements of pairwise distinct
degrees lies in `I` exactly when each summand does. -/
theorem ker_piecesToQuotient (I : Ideal (MvPolynomial (Fin n) k))
    (S : Set (MvPolynomial (Fin n) k)) (hS : ∀ f ∈ S, ∃ e, f.IsHomogeneous e)
    (hI : I = Ideal.span S) (T : ℕ) :
    LinearMap.ker (piecesToQuotient I T) =
      Submodule.pi Set.univ fun t : Fin T => idealPiece I (t : ℕ) := by
  ext v
  rw [LinearMap.mem_ker, piecesToQuotient_apply, Submodule.mem_pi]
  constructor
  · intro h t _
    have hg : (∑ s : Fin T, (v s : MvPolynomial (Fin n) k)) ∈ I := by
      rw [← Ideal.Quotient.eq_zero_iff_mem, map_sum]
      exact h
    have hcomp :
        homogeneousComponent (t : ℕ) (∑ s : Fin T, (v s : MvPolynomial (Fin n) k)) = v t := by
      rw [map_sum, Finset.sum_eq_single t]
      · rw [homogeneousComponent_of_mem (v t).2, if_pos rfl]
      · intro s _ hst
        rw [homogeneousComponent_of_mem (v s).2, if_neg fun hts => hst (Fin.ext hts.symm)]
      · intro ht
        exact absurd (Finset.mem_univ t) ht
    change (v t : MvPolynomial (Fin n) k) ∈ I
    rw [← hcomp, hI]
    exact homogeneousComponent_mem_ideal_span hS (hI ▸ hg) _
  · intro h
    refine Finset.sum_eq_zero fun t _ => ?_
    rw [Ideal.Quotient.eq_zero_iff_mem]
    exact h t (Set.mem_univ t)

/-- **Additivity of graded dimensions.** If `I` is generated by homogeneous elements and every
homogeneous polynomial of degree `≥ T` lies in `I`, then the `k`-dimension of `R ⧸ I` is the
sum of the dimensions of its graded pieces of degree `< T`. -/
theorem finrank_quotient_eq_sum_hdim (I : Ideal (MvPolynomial (Fin n) k))
    (S : Set (MvPolynomial (Fin n) k)) (hS : ∀ f ∈ S, ∃ e, f.IsHomogeneous e)
    (hI : I = Ideal.span S) [FiniteDimensional k (MvPolynomial (Fin n) k ⧸ I)] (T : ℕ)
    (hT : ∀ t, T ≤ t → homogeneousSubmodule (Fin n) k t ≤ Submodule.restrictScalars k I) :
    Module.finrank k (MvPolynomial (Fin n) k ⧸ I) = ∑ t ∈ Finset.range T, hdim I t := by
  classical
  have e : (MvPolynomial (Fin n) k ⧸ I) ≃ₗ[k]
      (t : Fin T) → (homogeneousSubmodule (Fin n) k (t : ℕ) ⧸ idealPiece I (t : ℕ)) :=
    ((LinearMap.quotKerEquivOfSurjective _ (surjective_piecesToQuotient I T hT)).symm.trans
      (Submodule.quotEquivOfEq _ _ (ker_piecesToQuotient I S hS hI T))).trans
      (Submodule.quotientPi _)
  rw [e.finrank_eq, Module.finrank_pi_fintype]
  exact Fin.sum_univ_eq_sum_range (fun t => hdim I t) T

end WeakBezout
